#!/bin/bash
# Generate inventory files for bot memory
# Called by push.sh before syncing
#
# Creates per-agent inventory files:
#   agents/{agent}/exports/Document Inventory.md

set -e

# Load shared functions
source "$(dirname "$0")/lib.sh"

# Load config
load_config

DATE=$(date +%Y-%m-%d)

# Helper: extract description from YAML frontmatter (fallback to title)
get_frontmatter_description() {
    local file="$1"
    # Look for description: in first 20 lines (frontmatter section)
    local desc=$(head -20 "$file" | grep -m1 "^description:" | sed 's/^description:[[:space:]]*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//')
    if [[ -z "$desc" ]]; then
        # Fallback: try title
        desc=$(head -20 "$file" | grep -m1 "^title:" | sed 's/^title:[[:space:]]*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//')
    fi
    if [[ -z "$desc" ]]; then
        # Final fallback: use filename without prefix
        desc=$(basename "$file" .md | sed 's/^[^-]*- //')
    fi
    echo "$desc"
}

# Helper: generate a section for files matching a pattern
# Args: section_name, base_dir, subdir, prefix
generate_section() {
    local section_name="$1"
    local base_dir="$2"
    local subdir="$3"
    local prefix="$4"
    local count=0
    local entries=""

    for f in "$base_dir/$subdir/$prefix"*.md; do
        [[ -f "$f" ]] || continue
        local name=$(basename "$f")
        local title=$(get_frontmatter_description "$f")
        local mdate=$(stat -f "%Sm" -t "%Y-%m-%d" "$f" 2>/dev/null || date +%Y-%m-%d)
        entries+="| $name | $title | $mdate |"$'\n'
        count=$((count + 1))
    done

    if [[ $count -gt 0 ]]; then
        echo "## $section_name ($count)"
        echo ""
        echo "| File | Description | Date |"
        echo "|------|-------------|------|"
        echo -n "$entries"
        echo ""
    fi
}

# Check if agent's include.scope contains transcripts
agent_has_transcript_scope() {
    local agent="$1"
    python3 -c "
import yaml
with open('config.yaml') as f:
    c = yaml.safe_load(f)
agent = c.get('agents', {}).get('$agent', {})
scopes = agent.get('include', {}).get('scope', [])
print('true' if 'transcripts' in scopes else 'false')
"
}

# Generate Document Inventory for an agent
generate_doc_inventory() {
    local agent="$1"
    local agent_export_dir="$2"

    if [[ ! -d "$agent_export_dir" ]]; then
        return
    fi

    local doc_count=0
    local prompt_count=0
    local refdoc_count=0
    for f in "$agent_export_dir/docs/Doc - "*.md; do [[ -f "$f" ]] && doc_count=$((doc_count + 1)); done
    for f in "$agent_export_dir/prompts/Prompt - "*.md; do [[ -f "$f" ]] && prompt_count=$((prompt_count + 1)); done
    for f in "$agent_export_dir/refdocs/Refdoc - "*.md; do [[ -f "$f" ]] && refdoc_count=$((refdoc_count + 1)); done

    if [[ $((doc_count + prompt_count + refdoc_count)) -gt 0 ]]; then
        {
            echo "# Document Inventory"
            echo ""
            echo "Generated: $DATE"
            echo ""
            generate_section "Docs" "$agent_export_dir" "docs" "Doc - "
            generate_section "Prompts" "$agent_export_dir" "prompts" "Prompt - "
            generate_section "Reference Docs" "$agent_export_dir" "refdocs" "Refdoc - "
            echo "---"
            echo "*Auto-generated by bruba-godo*"
        } > "$agent_export_dir/Document Inventory.md"
        echo "  $agent: Document Inventory: $doc_count docs, $prompt_count prompts, $refdoc_count refdocs"
    fi
}

# Generate Transcript Inventory for an agent (only if transcripts in scope)
generate_transcript_inventory() {
    local agent="$1"
    local agent_export_dir="$2"

    if [[ ! -d "$agent_export_dir/transcripts" ]]; then
        return
    fi

    local transcript_count=0
    for f in "$agent_export_dir/transcripts/Transcript - "*.md; do [[ -f "$f" ]] && transcript_count=$((transcript_count + 1)); done

    if [[ $transcript_count -gt 0 ]]; then
        {
            echo "# Transcript Inventory"
            echo ""
            echo "Generated: $DATE"
            echo ""
            generate_section "Transcripts" "$agent_export_dir" "transcripts" "Transcript - "
            echo "---"
            echo "*Auto-generated by bruba-godo*"
        } > "$agent_export_dir/Transcript Inventory.md"
        echo "  $agent: Transcript Inventory: $transcript_count transcripts"
    fi
}

# Main
echo "Generating inventories..."

# Iterate over content pipeline agents
CP_AGENTS=()
while IFS= read -r agent; do
    [[ -n "$agent" ]] && CP_AGENTS+=("$agent")
done < <(get_content_pipeline_agents)

for agent in "${CP_AGENTS[@]}"; do
    load_agent_config "$agent"
    generate_doc_inventory "$agent" "$AGENT_EXPORT_DIR"

    # Only generate transcript inventory if agent has transcripts in scope
    if [[ "$(agent_has_transcript_scope "$agent")" == "true" ]]; then
        generate_transcript_inventory "$agent" "$AGENT_EXPORT_DIR"
    fi
done
