#!/bin/bash
# Generate inventory files for bot memory
# Called by push.sh before syncing
#
# Creates:
#   exports/bot/Transcript Inventory.md - transcripts + summaries
#   exports/bot/Document Inventory.md - docs + prompts + refdocs + cc_logs

set -e

# Load shared functions
source "$(dirname "$0")/lib.sh"

# Load config to get EXPORTS_DIR
load_config

EXPORTS_BOT="$EXPORTS_DIR/bot"
DATE=$(date +%Y-%m-%d)

# Helper: extract description from YAML frontmatter (fallback to title)
get_frontmatter_description() {
    local file="$1"
    # Look for description: in first 20 lines (frontmatter section)
    local desc=$(head -20 "$file" | grep -m1 "^description:" | sed 's/^description:[[:space:]]*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//')
    if [[ -z "$desc" ]]; then
        # Fallback: try title
        desc=$(head -20 "$file" | grep -m1 "^title:" | sed 's/^title:[[:space:]]*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//')
    fi
    if [[ -z "$desc" ]]; then
        # Final fallback: use filename without prefix
        desc=$(basename "$file" .md | sed 's/^[^-]*- //')
    fi
    echo "$desc"
}

# Helper: generate a section for files matching a pattern
# Args: section_name, subdir, prefix
generate_section() {
    local section_name="$1"
    local subdir="$2"
    local prefix="$3"
    local count=0
    local entries=""

    for f in "$EXPORTS_BOT/$subdir/$prefix"*.md; do
        [[ -f "$f" ]] || continue
        local name=$(basename "$f")
        local title=$(get_frontmatter_description "$f")
        local mdate=$(stat -f "%Sm" -t "%Y-%m-%d" "$f" 2>/dev/null || date +%Y-%m-%d)
        entries+="| $name | $title | $mdate |"$'\n'
        count=$((count + 1))
    done

    if [[ $count -gt 0 ]]; then
        echo "## $section_name ($count)"
        echo ""
        echo "| File | Description | Date |"
        echo "|------|-------------|------|"
        echo -n "$entries"
        echo ""
    fi
}

# Generate Transcript Inventory (transcripts + summaries from canonical files)
generate_transcript_inventory() {
    local out="$EXPORTS_BOT/Transcript Inventory.md"
    local transcript_count=0
    local summary_count=0

    # Count files
    for f in "$EXPORTS_BOT/transcripts/Transcript - "*.md; do [[ -f "$f" ]] && transcript_count=$((transcript_count + 1)); done
    for f in "$EXPORTS_BOT/summaries/Summary - "*.md; do [[ -f "$f" ]] && summary_count=$((summary_count + 1)); done

    {
        echo "# Transcript Inventory"
        echo ""
        echo "Generated: $DATE"
        echo ""
        generate_section "Transcripts" "transcripts" "Transcript - "
        generate_section "Summaries" "summaries" "Summary - "
        echo "---"
        echo "*Auto-generated by bruba-godo*"
    } > "$out"

    echo "  Transcript Inventory: $transcript_count transcripts, $summary_count summaries"
}

# Generate Document Inventory (docs + prompts + refdocs + cc_logs)
generate_document_inventory() {
    local out="$EXPORTS_BOT/Document Inventory.md"
    local doc_count=0
    local prompt_count=0
    local refdoc_count=0
    local cclog_count=0

    # Count files
    for f in "$EXPORTS_BOT/docs/Doc - "*.md; do [[ -f "$f" ]] && doc_count=$((doc_count + 1)); done
    for f in "$EXPORTS_BOT/prompts/Prompt - "*.md; do [[ -f "$f" ]] && prompt_count=$((prompt_count + 1)); done
    for f in "$EXPORTS_BOT/refdocs/Refdoc - "*.md; do [[ -f "$f" ]] && refdoc_count=$((refdoc_count + 1)); done
    for f in "$EXPORTS_BOT/cc_logs/Claude Code Log - "*.md; do [[ -f "$f" ]] && cclog_count=$((cclog_count + 1)); done

    {
        echo "# Document Inventory"
        echo ""
        echo "Generated: $DATE"
        echo ""
        generate_section "Docs" "docs" "Doc - "
        generate_section "Prompts" "prompts" "Prompt - "
        generate_section "Reference Docs" "refdocs" "Refdoc - "
        generate_section "Claude Code Logs" "cc_logs" "Claude Code Log - "
        echo "---"
        echo "*Auto-generated by bruba-godo*"
    } > "$out"

    echo "  Document Inventory: $doc_count docs, $prompt_count prompts, $refdoc_count refdocs, $cclog_count cc_logs"
}

# Main
if [[ ! -d "$EXPORTS_BOT" ]]; then
    echo "No exports found at $EXPORTS_BOT"
    exit 1
fi

echo "Generating inventories..."
generate_transcript_inventory
generate_document_inventory
